export const GOTO_PAGE_TEACHER = 'GOTO_PAGE_TEACHER';

export const GOTO_PAGE_SCHEDULE = 'GOTO_PAGE_SCHEDULE';

export const SET_START_DATE = 'SET_START_DATE';

export const SET_END_DATE = 'SET_END_DATE';